### ISSUE TITLE
darned if I do darned if I don't -- the passing of blocks has issues

### ISSUE THREAD

**Issue by mistergibson** [Anyolite/anyolite#31]
class Thread
      def run(&block)
        @status = "running"
      end
end

gets me:

There was a problem expanding macro 'call_and_return_instance_method'

Code in macro 'new_rb_func'

 9 | __temp_64 = Anyolite::Macro.call_and_return_instance_method(_rb, run, __temp_63, __temp_62, operator: "", options: {:context => GxG::Engine::Thread, :return_nil => false, :block_arg_number => nil, :block_return_type => nil, :store_block_arg => false, :type_vars => [] of ::NoReturn, :type_var_names_annotation => nil, :type_var_names => nil}, block_ptr: __temp_61)
                 ^
Called macro defined in lib/anyolite/src/macros/FunctionCalls.cr:92:5

 92 | macro call_and_return_instance_method(rb, proc, converted_obj, converted_args, operator = "", options = {} of Symbol => NoReturn, block_ptr = nil)

Which expanded to:

 >  7 | 
 >  8 |         
 >  9 |           __temp_78 = __temp_77.run(*__temp_62) 
                                       ^--
Error: 'GxG::Engine::Thread#run' is expected to be invoked with a block, but no block was given

so if I remove the &block arg it will wrap, but when I call it with a block it complains that this method doesn't receive blocks

What am I doing wrong here -- I don't see it.

**Comment by Hadeweka** [comment]
There are a couple things to keep in mind here:

Anyolite does not work with block arguments using the `&block`-syntax, as they have no type specified. Since Anyolite needs to know exactly which types are passed and returned at runtime, this restriction cannot be removed.

But Anyolite has two ways to work around this, depending on your use case.
Please refer to the official Anyolite Wiki for them:

https://github.com/Anyolite/anyolite/wiki/Passing-block-arguments

Passing blocks as arguments is still a bit restricted, but most use cases should be able to be covered with the methods described there.

**Comment by Hadeweka** [comment]
Edited the title to describe the problem more clearly and objectively
