### ISSUE TITLE
This is a query, and not an issue....

### ISSUE THREAD

**Issue by wyhaines** [Anyolite/anyolite#5]
Do you know, offhand, what the barriers are to porting this work to apply against standard MRI Ruby instead of mruby?

I have done some experimentation with manual bindings between Crystal and Ruby (embedding Ruby into a Crystal program), and for some trivial things, it worked better than I expected.

i.e. Bind Ruby 3 into Crystal, load code from an external file into the Ruby VM, call Crystal code with rb_protect to, in turn, invoke Ruby methods, capturing the return VALUE and transforming that to equivalent Crystal data structures (Strings).

An awful lot of what I see in anyolite looks like things that I would want to implement to enable less trivial, and less manual binding between Crystal and Ruby, so I am wondering if you are aware of any major gotchas to doing so?

**Comment by Hadeweka** [comment]
As far as I'm aware the API functions of mruby and MRI are very similar to each other, so this should not be a big problem (though I haven't yet tried it).

What exactly did you have in mind for the last paragraph? Is there anything you're missing in Anyolite what could be improved using MRI (except for obvious things like speed and ecosystem)?

**Comment by wyhaines** [comment]
Mostly speed and ecosystem. honestly. Interoperability that manages to avoid tripping over garbage collection provides some interesting opportunities, and while I was already hatching some ideas in my head for how to achieve this, it looks like you've already done a fair amount of the hard thinking and typing work.

I might take what you have done, fork it, and marry it with a few things that I have been hacking on to see if I can get a proof of concept to link with MRI Ruby.

**Comment by Hadeweka** [comment]
It would definitely be cool to see how switching to MRI improves certain aspects!

Garbage collecting was a problem I fixed by implementing a reference table in Crystal, which keeps track of all shared objects, and by giving a customized destructor method to all shared mruby objects. It is not the most sophisticated approach, but it should prevent any internal dangling pointers and segfaults. If MRI provides a method to give custom destructor methods to data objects, the concept can easily be ported.

**Comment by anykeyh** [comment]
I just thumb up as I wish to see this coming.

I'm currently working on an actor framework inspired by Akka and want to create ruby actors, allowing the use of ruby ecosystem, zero compilation time and still being able to run some performance-needed portion in crystal. 

I'm not sure it's so easy to port MRI however.

**Comment by Hadeweka** [comment]
Support for MRI is on the roadmap for future versions and I already built some of the infrastructure to support different Ruby implementations.

Most of the work will be mapping all implementation-dependent functions to the respective MRI functions instead of the mruby functions, probably some changes in the installation process and lots of testing.

There are also some implementation details I haven't figured out completely, like gem support or dealing with the differences in argument passing, so don't expect it too soon.

**Comment by Hadeweka** [comment]
Aaaand it's done!

MRI 3.0.2 can be selected as an alternative implementation to Anyolite now (mruby is still recommended, though)! Instructions are in the README file.

There might be some weird bugs or inconveniencies (like the broken documentation - I'll fix it in the next days), but the test scenario runs completely fine.

Gem installation is also only possible manually, but it should work fine.

That also means that this issue can (finally) be closed.

If you have any other questions or comments, feel free to join the discussion thread under the 0.13.0 release.

**Comment by wyhaines** [comment]
Sweet!!!!!

I am going to be giving this a workout soon.
